# Generated by Django 2.2.12 on 2020-04-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_load_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="ccc",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customtext",
            name="ddd",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
